EASYOPAC-963 - Ajust admin form, add fonts.
easySuite/easyopac_status pull request #6
Opened 2018-09-11 12:32 UTC by NicolaeGrigoriu

2018-09-11 12:54 UTC, guddo requested changes

2018-09-11 12:54 UTC, guddo commented on sass/easyopac_status.scss
> +  .critical {
Why not move `font-size: 55px;` and `font-family: 'icomoon';` to generic selector instead of defining it 5 times?

2018-09-11 12:54 UTC, guddo commented on js/easyopac_status.js
> +        // debugger;
Woops

2018-09-11 12:54 UTC, guddo commented on js/easyopac_status.js
> +          // .find('.message').css('color', Drupal.settings.easyopac_status.settings.text_color)
Woops

2018-09-11 19:20 UTC, NicolaeGrigoriu commented
This is still work in progress. These changes are committed in order to move to another task and not to lose them.

2018-10-16 14:05 UTC, bozeak commented
CR ok. @guddo ^^

2018-10-16 16:03 UTC, guddo approved these changes

2018-10-16 16:03 UTC, merged